### ISSUE TITLE
With the code

### ISSUE THREAD

**Issue by A7777-gp** [hellojialee/OffsetGuided#2]
Thank you very much，I have benefited a lot from reading your code，As a beginner，How can I write this code as well as you！！😁

**Comment by hellojialee** [comment]
Thank you for your interest. Your words really flattered me. I feel so happy that this repo may provide some help. Feel free to discuss with me.

**Comment by A7777-gp** [comment]
It's my pleasure.I have the following questions:

1. Is the keypoint heatmap marked at the beginning of the data set? and how is the heatmap generated？
2.  I downloaded your code which is divided into several packages.This looks complicated,I want to know if all of this code needs to be written from zero?
I am looking forward to your reply！！哈哈😁

**Comment by A7777-gp** [comment]
It's my pleasure.I have the following questions:

1. Is the keypoint heatmap marked at the beginning of the data set? and how is the heatmap generated？
2.  I downloaded your code which is divided into several packages.This looks complicated,I want to know if all of this code needs to be written from zero?
I am looking forward to your reply！！😁

**Comment by A7777-gp** [comment]
It's my pleasure.I have the following questions:

1.Is the keypoint heatmap marked at the beginning of the data set? and how is the heatmap generated？
2.I downloaded your code which is divided into several packages.This looks complicated,I want to know if all of this code needs to be written from zero?Or it can be modified from someone else's base
I am looking forward to your reply！！😁

**Comment by hellojialee** [comment]
1. The ground truth is generated in OffsetGuided/encoder during training process.
2. I borrow some code from others' and then build my codebase from scratch such that the code style follows my preferences. You should make sure your code or other people's code is reliable.

FYI: As a green hand, I recommend you write your first code from zero. But the dirty and hard work couldn't help you publish a good research paper.

**Comment by A7777-gp** [comment]
Thank you very much for taking the time to answer my question.I want to try to improve from the two papers you published on Simplepose, I think it's hard to change from the network structure, or should I use some other Keypoint matching algorithm to improve it?Could you give me some guidance?
Most important: I find it really hard to change code！！！😭

**Comment by hellojialee** [comment]
The greedy grouping algorithm is not easy to implement for beginners. You definitely should refer to more methods. You can do what you want if you continue to learn. 
Best wishes!

**Comment by A7777-gp** [comment]
Thanks！I will be try. I'm going to read more papers next and looking forward to further communication with you！

**Comment by hellojialee** [comment]
No problem :)
